/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "#364247",
          dark: "#2a3337",
          light: "#4a5459",
          lighter: "#e8eaeb",
          cream: "#f9f6ee",
        },
        // Design-token bridge (Design.md section 1) — semantic names resolve
        // to the CSS custom properties defined on body / body[data-theme="dark"].
        bg: "var(--bg)",
        surface: "var(--surface)",
        line: "var(--line)",
        hair: "var(--hair)",
        ink: "var(--ink)",
        ink2: "var(--ink2)",
        "ui-body": "var(--body)",
        soft: "var(--soft)",
        mut: "var(--mut)",
        mut2: "var(--mut2)",
        chip: "var(--chip)",
        panel: "var(--panel)",
        brandink: "var(--brandink)",
        link: "var(--link)",
        headbg: "var(--headbg)",
        headline: "var(--headline)",
        panelbrd: "var(--panelbrd)",
        ghost: "var(--ghost)",
        ghostbrd: "var(--ghostbrd)",
        warnbg: "var(--warnbg)",
        warnbg2: "var(--warnbg2)",
        warnbrd: "var(--warnbrd)",
        warnink: "var(--warnink)",
        warnmut: "var(--warnmut)",
        warnbadge: "var(--warnbadge)",
        advbg: "var(--advbg)",
        advbrd: "var(--advbrd)",
        advink: "var(--advink)",
        advmut: "var(--advmut)",
        advbdg: "var(--advbdg)",
        calh: "var(--calh)",
        calhb: "var(--calhb)",
        calf: "var(--calf)",
        calfb: "var(--calfb)",
        calp: "var(--calp)",
        calpb: "var(--calpb)",
        barbg: "var(--barbg)",
      },
      fontFamily: {
        serif: ['"Source Serif 4"', "serif"],
      },
      borderRadius: {
        control: "2px",
        card: "3px",
      },
      boxShadow: {
        card: "var(--csh)",
      },
    },
  },
  plugins: [],
};
